name: rescuemule
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  elbe: ^0.2.8
  bluetooth_low_energy: ^6.0.2
  flutter_chat_ui: ^2.1.3
  shared_preferences: ^2.5.3
  flutter_chat_core: ^2.2.0
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.5.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/esel_pixabay.mp3
